# Generated by Django 4.2.25 on 2025-11-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigimage',
            old_name='hash',
            new_name='image_hash',
        ),
        migrations.AddField(
            model_name='bigimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bigimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mosaictile',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
