# Generated by Django 4.2.25 on 2025-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_rename_hash_bigimage_image_hash_bigimage_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigimage',
            name='column_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bigimage',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bigimage',
            name='tile_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bigimage',
            name='tile_width',
            field=models.IntegerField(default=0),
        ),
    ]
