# Generated by Django 4.2.25 on 2025-11-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_bigimage_column_count_bigimage_row_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999999)),
                ('email_to_me', models.BooleanField()),
                ('email', models.CharField(max_length=200)),
                ('print', models.BooleanField()),
                ('print_in_mosaic', models.BooleanField()),
            ],
        ),
    ]
